version: 0.2

phases:
  build:
    commands:
      - echo Test started on `date`
      - echo Running Test...
  post_build:
    commands:
      - echo Test completed on `date`
artifacts:
  files:
    - application.py
    - requirements.txt
    - downloader.py
    - .ebextensions/**/*
