version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      #- python eb_worker_test.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - application.py
    - requirements.txt
    - scraper.py
    - .ebextensions
